# Generated by Django 3.2.5 on 2021-10-18 09:25

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
                ('flag', models.CharField(max_length=10)),
                ('code', models.CharField(max_length=5)),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.BinaryField(default=1)),
                ('image', models.ImageField(upload_to='category')),
                ('date_modified', models.DateField(default=datetime.date.today)),
                ('parent', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='children', to='product.category')),
            ],
        ),
    ]
