# Generated by Django 3.2.5 on 2021-10-20 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_auto_20211018_2007'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='name',
            field=models.CharField(default='Category', max_length=20),
        ),
        migrations.AlterField(
            model_name='category',
            name='status',
            field=models.IntegerField(default=1),
        ),
    ]
