# Generated by Django 3.2.5 on 2021-10-20 07:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_auto_20211020_1204'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category_seo',
            name='language_code',
        ),
        migrations.AddField(
            model_name='category_seo',
            name='language',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='product.language'),
        ),
    ]
