# Generated by Django 4.2 on 2023-10-18 03:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Paypal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=10)),
                ('status', models.BooleanField(default=0)),
                ('sandbox', models.BooleanField(default=1)),
                ('transaction', models.CharField(choices=[('Auth', 'Authorization'), ('Sale', 'Sale')])),
                ('sort_order', models.IntegerField(default=10)),
            ],
        ),
    ]
