# Generated by Django 4.2 on 2023-12-09 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(default='', max_length=10)),
                ('title', models.CharField(default='Payment Title', max_length=20)),
                ('status', models.BooleanField(default=0)),
            ],
        ),
    ]
