# Generated by Django 4.2 on 2023-12-14 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tax',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
                ('type', models.CharField(choices=[('A', 'Absolute Value'), ('P', 'Percentage')], default='P')),
                ('status', models.BooleanField(default=1)),
                ('sort_order', models.IntegerField(default=1)),
                ('rate', models.DecimalField(decimal_places=2, max_digits=4)),
            ],
        ),
    ]
