# Generated by Django 4.2 on 2023-12-21 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taxes', '0005_alter_tax_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tax',
            name='type',
            field=models.CharField(choices=[('A', 'Absolute Value'), ('P', 'Percentage')], default='P'),
        ),
    ]
