# Generated by Django 4.2 on 2024-02-07 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taxes', '0019_alter_tax_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tax',
            name='type',
            field=models.CharField(choices=[('A', 'Absolute Value'), ('P', 'Percentage')], default='P'),
        ),
    ]
