# Generated by Django 4.2 on 2024-04-25 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taxes', '0022_alter_tax_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tax',
            name='type',
            field=models.CharField(choices=[('P', 'Percentage'), ('A', 'Absolute Value')], default='P'),
        ),
    ]
