# Generated by Django 4.2 on 2023-10-12 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cod', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cod',
            name='sort_order',
            field=models.SmallIntegerField(default=10),
        ),
    ]
