# Generated by Django 3.2.5 on 2021-10-18 08:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tsettings', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.BinaryField(default=1)),
                ('date_added', models.DateField(default=datetime.date(2021, 10, 18))),
            ],
        ),
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
                ('flag', models.CharField(max_length=10)),
                ('code', models.CharField(max_length=5)),
            ],
        ),
    ]
