# Generated by Django 3.2.5 on 2021-10-18 09:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tsettings', '0002_category_language'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Category',
        ),
        migrations.DeleteModel(
            name='Language',
        ),
    ]
