# Generated by Django 4.2 on 2023-12-27 05:49

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orders', '0010_order_customer_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='CheckoutKey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_id', models.CharField(blank=True)),
                ('customer_id', models.IntegerField(blank=True)),
                ('key', models.CharField(max_length=100)),
                ('created', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.order')),
            ],
        ),
        migrations.AddConstraint(
            model_name='checkoutkey',
            constraint=models.UniqueConstraint(fields=('key',), name='unique_otkey'),
        ),
    ]
