# Generated by Django 4.2 on 2023-12-10 01:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0004_appcart'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AppCart',
        ),
    ]
