# Generated by Django 4.2 on 2023-12-15 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0005_delete_appcart'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='device_id',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
