# Generated by Django 4.2 on 2023-12-16 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0006_book_device_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='device_id',
            field=models.CharField(blank=True, max_length=150),
        ),
    ]
