# Generated by Django 4.2 on 2023-12-18 01:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0007_alter_book_device_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='user',
        ),
        migrations.AddField(
            model_name='book',
            name='email',
            field=models.CharField(blank=True, default='demo@gmail.com', max_length=150),
        ),
        migrations.AddField(
            model_name='book',
            name='name',
            field=models.CharField(default='demo@gmail.com', max_length=60),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='book',
            name='phone',
            field=models.CharField(default=93939393939, max_length=15),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='book',
            name='user_id',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
