# Generated by Django 4.2 on 2023-12-18 06:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_order_device_id'),
        ('service', '0009_book_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='order',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='orders.order'),
        ),
    ]
