# Generated by Django 4.2 on 2023-12-21 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0010_alter_book_order'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sspecial',
            options={'verbose_name': 'Service Special Day', 'verbose_name_plural': 'Service Special Days'},
        ),
        migrations.AlterField(
            model_name='book',
            name='status',
            field=models.CharField(choices=[('UN', 'UNAVAILABLE'), ('AV', 'AVAILABLE'), ('CAN', 'CANCELLED'), ('BOOKED', 'BOOKED')], default='AV', max_length=15),
        ),
    ]
