# Generated by Django 4.2 on 2023-12-21 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0012_remove_book_order_alter_book_service'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='order_id',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
