# Generated by Django 4.2 on 2023-12-21 14:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0014_book_unique_booking'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='book',
            name='unique_booking',
        ),
    ]
