# Generated by Django 4.2 on 2024-03-06 04:41

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0018_remove_bookhistory_book_remove_book_unique_booking_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='extra_info',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.CreateModel(
            name='BookHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dated', models.DateField(default=django.utils.timezone.now, max_length=20)),
                ('status', models.CharField(max_length=20)),
                ('book_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='service.book')),
            ],
        ),
    ]
