# Generated by Django 4.2 on 2024-04-24 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0020_bookhistory_info_alter_book_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fbstring', models.CharField(blank=True, max_length=150)),
                ('ntype', models.CharField(choices=[('BOOK', 'Book'), ('ORD', 'Order')], max_length=7)),
                ('msg', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
