# Generated by Django 4.2 on 2024-05-11 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0021_appnotification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sspecial',
            name='sdate',
            field=models.DateField(),
        ),
    ]
