# Generated by Django 4.2 on 2023-12-29 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guser', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='guser',
            old_name='key',
            new_name='access',
        ),
        migrations.AddField(
            model_name='guser',
            name='refresh',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
