# Generated by Django 4.2 on 2024-01-01 04:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guser', '0002_rename_key_guser_access_guser_refresh'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guser',
            name='access',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AlterField(
            model_name='guser',
            name='refresh',
            field=models.CharField(blank=True, max_length=150),
        ),
    ]
