# Generated by Django 4.2 on 2024-01-01 04:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guser', '0003_alter_guser_access_alter_guser_refresh'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guser',
            name='access',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AlterField(
            model_name='guser',
            name='refresh',
            field=models.CharField(blank=True, max_length=250),
        ),
    ]
