# Generated by Django 4.2 on 2024-05-30 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('information', '0002_alter_information_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='information',
            name='sort_order',
            field=models.IntegerField(default=10),
        ),
    ]
