# Generated by Django 4.2 on 2023-12-10 01:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('service', '0005_delete_appcart'),
        ('customer', '0002_alter_customer_phone'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppCart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dated', models.DateField(max_length=20)),
                ('slot', models.CharField(max_length=20)),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='service.service')),
                ('user', models.ForeignKey(blank=True, default='shambhal', on_delete=django.db.models.deletion.CASCADE, to='customer.customer')),
            ],
        ),
    ]
