# Generated by Django 4.2 on 2023-12-16 10:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0002_alter_customer_phone'),
        ('cart', '0002_appcart_device_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appcart',
            name='user',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='customer.customer'),
        ),
    ]
