# Generated by Django 4.2 on 2023-12-18 01:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_alter_order_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='currency_code',
            field=models.CharField(blank=True, max_length=4),
        ),
    ]
