# Generated by Django 4.2 on 2023-12-21 10:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0012_remove_book_order_alter_book_service'),
        ('orders', '0007_order_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitems',
            name='service',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='service.service'),
        ),
    ]
