# Generated by Django 4.2 on 2023-12-26 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0009_orderhistory'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='customer_id',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
