# Generated by Django 4.2 on 2024-01-01 15:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0010_order_customer_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='customer_id',
            new_name='user_id',
        ),
    ]
